package se.kth.iv1350.sem4pos.model;

/**
 * The data transfer object containing the item registration information
 *              generated by the <code>registerItem</code> method existing in the {@link Sale} class.
 *              Instances are immutable.
 */
public final class RegistrationInfoDTO {
    private String itemDescription;
    private double itemPriceInclVAT;
    private double runningTotalInclVAT;

    /**
     * Creates a new instance of the {@link RegistrationInfoDTO} class.
     * @param itemDescription The description of the registered item.
     * @param itemPriceInclVAT The price of the registered item including VAT.
     * @param runningTotalInclVAT The running total of the current sale including VAT.
     */
    RegistrationInfoDTO(String itemDescription, double itemPriceInclVAT, double runningTotalInclVAT)
    {
        this.itemDescription = itemDescription;
        this.itemPriceInclVAT = itemPriceInclVAT;
        this.runningTotalInclVAT = runningTotalInclVAT;
    }

    /**
     * Returns the description of the registered item.
     * @return The description of the registered item.
     */
    public String getItemDescription() {
        return itemDescription;
    }

    /**
     * Returns the price of the registered item including VAT.
     * @return The price of the registered item including VAT.
     */
    public double getItemPriceInclVAT() {
        return itemPriceInclVAT;
    }

    /**
     * Returns the running total of the current sale including VAT.
     * @return The running total of the current sale including VAT.
     */
    public double getRunningTotalInclVAT() {
        return runningTotalInclVAT;
    }
}
